apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxy
spec:
  rules:
    - host: movies.cinema.pl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: movies-service
                port:
                  number: 8080
    - host: payment.cinema.pl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: payment-service
                port:
                  number: 8080
    - host: ticket.cinema.pl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ticket-service
                port:
                  number: 8080
