apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-service
spec:
  selector:
    matchLabels:
      app: ticket-service
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: ticket-service
        tier: backend
        track: stable
    spec:
      containers:
        - name: movies
          image: spokospartan/ticket:0.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVER_PORT
              value: "8080"
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "300Mi"
              cpu: "400m"
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 300
            periodSeconds: 20
